# Generated by Django 4.2.2 on 2023-06-27 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_category_alter_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='likes_n',
        ),
    ]
