# Generated by Django 4.2.2 on 2023-06-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blog_likes_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='likes_n',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
