# Generated by Django 4.2.2 on 2023-06-29 20:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_blog_likes_n'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='likes_n',
        ),
        migrations.AddField(
            model_name='blog',
            name='likes_n',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
