# Generated by Django 4.2.2 on 2023-06-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_blog_likes_n_blog_likes_n'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='likes_n',
        ),
        migrations.AddField(
            model_name='blog',
            name='likes_n',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
